apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: httpbin-test
spec:
  type: NodePort
  selector:
    app: httpbin
  ports:
    - port: 80         # Port interne du service
      targetPort: 80   # Port du conteneur
      nodePort: 30080  # Port accessible depuis l'extérieur du cluster
