elasticsearchHosts: "https://elasticsearch.elk.svc.cluster.local:9200"
elasticsearchSSL:
  certificateAuthorities:
    - /usr/share/kibana/config/certs/tls.crt
extraVolumes:
  - name: certs
    secret:
      secretName: elasticsearch-cert
extraVolumeMounts:
  - name: certs
    mountPath: /appli/elk/kibana/config/certs
    readOnly: true
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: kibana.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific