elasticsearchHosts: "https://elasticsearch-master.elk.svc.cluster.local:9200"
elasticsearchSSL:
  certificateAuthorities:
    - /usr/share/kibana/config/certs/tls.crt
extraVolumes:
  - name: certs
    secret:
      secretName: elasticsearch-cert
extraVolumeMounts:
  - name: certs
    mountPath: /usr/share/kibana/config/certs
    readOnly: true
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: kibana.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - kibana.example.com
      secretName: kibana-tls-cert
